### ISSUE TITLE
OptEco not loading correctly.

### ISSUE THREAD

**Issue by SirBlobman** [PlayerNguyen/OptEco#28]
**Describe the bug**
OptEco has an error being enabled with Vault 1.7.3 and ShopGUIPlus 1.54.0 on Paper 1.15.2

**To Reproduce**
1. Install Paper 1.15.2
2. Install OptEco, Vault, ShopGUIPlus, and EssentialsX
3. Check console and see the error.

**Expected behavior**
OptEco to load correctly

**Information:**
```
[18:37:34 INFO]: [OptEco] Enabling OptEco v2.1.1b
[18:37:34 INFO]: [OptEco] Loading storage type.
[18:37:34 INFO]: [OptEco] Current storage type: sqlite
[18:37:34 INFO]: [OptEco] Setup storage and accounts...
[18:37:34 INFO]: [OptEco] Loading listeners.
[18:37:34 INFO]: [OptEco] Loading commands.
[18:37:34 INFO]: [OptEco] Found ShopGuiPlus. Registering provider...
[18:37:34 ERROR]: [OptEco] Having a critical problem when loading plugin :( <~> ):
[18:37:34 WARN]: java.lang.NullPointerException
[18:37:34 WARN]:        at net.brcdev.shopgui.ShopGuiPlusApi.registerEconomyProvider(ShopGuiPlusApi.java:315)
[18:37:34 WARN]:        at me.playernguyen.opteco.api.shopguiplus.OptEcoShopGuiPlusEconomyProvider.register(OptEcoShopGuiPlusEconomyProvider.java:19)
[18:37:34 WARN]:        at me.playernguyen.opteco.OptEco.hookShopGuiPlus(OptEco.java:104)
[18:37:34 WARN]:        at me.playernguyen.opteco.OptEco.onEnable(OptEco.java:77)
[18:37:34 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:37:34 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[18:37:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[18:37:34 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
[18:37:34 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
[18:37:34 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[18:37:34 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[18:37:34 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909)
[18:37:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

```
[18:42:50 INFO]: This server is running Paper version git-Paper-391 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[18:42:50 INFO]: Checking version, please wait...
[18:42:51 INFO]: You are running the latest version
```

```
[18:39:05 INFO]: OptEco version 2.1.1b
[18:39:05 INFO]: The powerful points system plugin of Minecraft Server
[18:39:05 INFO]: Author: Player_Nguyen

[18:43:23 INFO]: ShopGUIPlus version 1.54.0
[18:43:23 INFO]: Author: brc

[18:43:32 INFO]: Vault version 1.7.3-b131
[18:43:32 INFO]: Vault is a Permissions & Economy API to allow plugins to more easily hook into these systems without needing to hook each individual system themselves.
[18:43:32 INFO]: Website: https://dev.bukkit.org/projects/vault
[18:43:32 INFO]: Authors: cereal, Sleaker and mung3r

[18:43:42 INFO]: Essentials version 2.19.0-dev+99-1e0d7fb
[18:43:42 INFO]: Provides an essential, core set of commands for Bukkit.
[18:43:42 INFO]: Website: https://essentialsx.net/
[18:43:42 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam and md678685
```

**Additional context**
There was also an issue reported in the ShopGUIPlus discord about OptEco overriding Vault when EssentialsX is installed, not sure if its related.

**Comment by PlayerNguyen** [comment]
Fixed by @SirBlobman
