### ISSUE TITLE
possible mysql issue

### ISSUE THREAD

**Issue by super7800** [PlayerNguyen/OptEco#31]
i believe i have setup mysql correctly, as I have dozens of other plugins using it fine, including an older version of opt eco running on a different server project. here is the console error log:

`[10:10:17 INFO]: OptEco - Starting...
[10:10:17 ERROR]: Having a critical problem when loading plugin :( <~> ):
[10:10:17 WARN]: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
[10:10:17 WARN]: 	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:113)
[10:10:17 WARN]: 	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:332)
[10:10:17 WARN]: 	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:109)
[10:10:17 WARN]: 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[10:10:17 WARN]: 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[10:10:17 WARN]: 	at me.playernguyen.opteco.sql.MySQLEstablish.openConnect(MySQLEstablish.java:71)
[10:10:17 WARN]: 	at me.playernguyen.opteco.sql.MySQLEstablish.getTables(MySQLEstablish.java:83)
[10:10:17 WARN]: 	at me.playernguyen.opteco.sql.SQLEstablish.createTableIfNotExist(SQLEstablish.java:57)
[10:10:17 WARN]: 	at me.playernguyen.opteco.sql.SQLEstablish.setupTable(SQLEstablish.java:87)
[10:10:17 WARN]: 	at me.playernguyen.opteco.account.SQLAccountDatabase.<init>(SQLAccountDatabase.java:25)
[10:10:17 WARN]: 	at me.playernguyen.opteco.account.mysql.MySQLAccountDatabase.<init>(MySQLAccountDatabase.java:26)
[10:10:17 WARN]: 	at me.playernguyen.opteco.OptEco.registerAccountDatabase(OptEco.java:344)
[10:10:17 WARN]: 	at me.playernguyen.opteco.OptEco.setupAccount(OptEco.java:193)
[10:10:17 WARN]: 	at me.playernguyen.opteco.OptEco.onEnable(OptEco.java:80)
[10:10:17 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:10:17 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[10:10:17 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[10:10:17 WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
[10:10:17 WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
[10:10:17 WARN]: 	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
[10:10:17 WARN]: 	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[10:10:17 WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[10:10:17 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:10:17 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:10:17 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120)
[10:10:17 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[10:10:17 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[10:10:17 WARN]: Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
[10:10:17 WARN]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
[10:10:17 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182)
[10:10:17 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
[10:10:17 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[10:10:17 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[10:10:17 WARN]: 	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:100)
[10:10:17 WARN]: 	... 41 more
[10:10:17 INFO]: Disabling OptEco because of error
[10:10:17 INFO]: [OptEco::Debug] §7Found next version of: 2.1.2b
[10:10:17 INFO]: §eDetected new update (2.1.2b), download at https://www.spigotmc.org/resources/76179
`
![opteco issue](https://user-images.githubusercontent.com/18103786/115154379-1c6a1f00-a040-11eb-845b-bb3394088280.PNG)

it says i need the latest version, but i am already using the latest version. is this an issue with my mysql setup, or with your plugin? and how would i fix it? Minecraft paper 1.16.5. thanks. let me know any further details you need.

**Comment by PlayerNguyen** [comment]
Fixed in 2.1.3b
