### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by Fathari** [PlayerNguyen/OptEco#32]
```
[09:04:26 ERROR]: Error occurred while enabling OptEco v2.1.2b-devbuild (Is it up to date?)
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
        at me.playernguyen.opteco.sql.MySQLEstablish.<init>(MySQLEstablish.java:31) ~[?:?]
        at me.playernguyen.opteco.account.mysql.MySQLAccountDatabase.<init>(MySQLAccountDatabase.java:26) ~[?:?]
        at me.playernguyen.opteco.OptEco.registerAccountDatabase(OptEco.java:344) ~[?:?]
        at me.playernguyen.opteco.OptEco.setupAccount(OptEco.java:193) ~[?:?]
        at me.playernguyen.opteco.OptEco.onEnable(OptEco.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-604]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-604]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-604]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-604]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-604]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-604]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-604]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-604]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-604]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-604]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-604]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader
```

How to Fix That?

**Comment by super7800** [comment]
i think i'm having the same issue as you (see the issue i also opened).  Could you post your config? thanks

**Comment by Hontiris1** [comment]
> i think i'm having the same issue as you (see the issue i also opened). Could you post your config? thanks

I'm having the same error you are both having. And my configuration is set up correctly just like yours.

**Comment by Fathari** [comment]
> i think i'm having the same issue as you (see the issue i also opened). Could you post your config? thanks

![image](https://user-images.githubusercontent.com/82939036/116011721-986ff280-a650-11eb-8602-cd1b9be8ab92.png)
this my config

**Comment by Hontiris1** [comment]
No need to post an image because we all have the same configuration.

**Comment by ahdg6** [comment]
It seems that the file uploaded in spigot is wrong.
Try this,rename to .jar
[OptEco-2.1.2b-devbuild.jar.zip](https://github.com/PlayerNguyen/OptEco/files/6411991/OptEco-2.1.2b-devbuild.jar.zip)

**Comment by PlayerNguyen** [comment]
Fixed by version 2.1.3, thanks for reporting 😇
My apology when being late
