### ISSUE TITLE
MySql Error

### ISSUE THREAD

**Issue by Ranslsad** [PlayerNguyen/OptEco#34]
Hello, in the new spigot updates the MySql connection not works, i tried last version and sqllite works but mysql not working.

Is there any update planned?

Thanks

**Comment by Hontiris1** [comment]
Yup this has been reported already but we are waiting for the author to fix it now.

**Comment by Ranslsad** [comment]
Thanks, this issue is very important, because i cant update my spigot and there is security issues with it, any news about any solution?

**Comment by Ranslsad** [comment]
I saw a new update, but still not working mysql connection, tried with ssl true and false.
```

[15:36:17] [Server thread/INFO]: [OptEco] Enabling OptEco v2.1.3b
[15:36:17] [Server thread/INFO]: [OptEco] Loading storage type.
[15:36:17] [Server thread/INFO]: [OptEco] Current storage type: mysql
[15:36:17] [Server thread/INFO]: [OptEco] Setup storage and accounts...
[15:36:17] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] OptEco - Starting...
[15:36:17] [Server thread/ERROR]: [OptEco] Having a critical problem when loading plugin :( <~> ):
[15:36:17] [Server thread/WARN]: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://DBIP:3306/DBNAME?useSSL=true
[15:36:17] [Server thread/WARN]: 	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
[15:36:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:325)
[15:36:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
[15:36:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[15:36:17] [Server thread/WARN]: 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[15:36:17] [Server thread/WARN]: 	at me.playernguyen.opteco.sql.MySQLEstablish.openConnect(MySQLEstablish.java:46)
[15:36:17] [Server thread/WARN]: 	at me.playernguyen.opteco.sql.MySQLEstablish.getTables(MySQLEstablish.java:58)
[15:36:17] [Server thread/WARN]: 	at me.playernguyen.opteco.sql.SQLEstablish.createTableIfNotExist(SQLEstablish.java:57)
[15:36:17] [Server thread/WARN]: 	at me.playernguyen.opteco.sql.SQLEstablish.setupTable(SQLEstablish.java:87)
[15:36:17] [Server thread/WARN]: 	at me.playernguyen.opteco.account.SQLAccountDatabase.<init>(SQLAccountDatabase.java:25)
[15:36:17] [Server thread/WARN]: 	at me.playernguyen.opteco.account.mysql.MySQLAccountDatabase.<init>(MySQLAccountDatabase.java:26)
[15:36:17] [Server thread/WARN]: 	at me.playernguyen.opteco.OptEco.registerAccountDatabase(OptEco.java:344)
[15:36:17] [Server thread/WARN]: 	at me.playernguyen.opteco.OptEco.setupAccount(OptEco.java:193)
[15:36:17] [Server thread/WARN]: 	at me.playernguyen.opteco.OptEco.onEnable(OptEco.java:80)
[15:36:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:36:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[15:36:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[15:36:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[15:36:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[15:36:17] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591)
[15:36:17] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281)
[15:36:17] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
[15:36:17] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[15:36:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[15:36:17] [Server thread/WARN]: Caused by: java.sql.SQLException: No suitable driver
[15:36:17] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298)
[15:36:17] [Server thread/WARN]: 	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
[15:36:17] [Server thread/WARN]: 	... 23 more
[15:36:17] [Server thread/INFO]: [OptEco] Disabling OptEco because of error
```

**Comment by PlayerNguyen** [comment]
Excuse me, can I know your Spigot version and more details about it?

**Comment by Ranslsad** [comment]
Im trying to use with last paper spigot version: 643 at this moment.
With version paper-472 paper spigot and OptEco-2.1.1b works well, but when i try to update to newer versions, Mysql connection not works.

**Comment by Ranslsad** [comment]
Hello, still cant update my server beause dont work on new 1.16 paper spigot versions, anyone knows what can i do?
screen of the error:
![error](https://user-images.githubusercontent.com/83597382/124767588-3bd66100-df38-11eb-80ba-4f59d00b722c.png)

@PlayerNguyen
