### ISSUE TITLE
warn spammed in console

### ISSUE THREAD

**Issue by Tsotne336** [PlayerNguyen/OptEco#36]
[13:38:11] [Craft Scheduler Thread - 5019/WARN]: Exception in thread "Craft Scheduler Thread - 5019" 
[13:38:11] [Craft Scheduler Thread - 5019/WARN]: org.apache.commons.lang.UnhandledException: Plugin OptEco v2.1.3b generated an exception while executing task 206
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.sendTitle(Ljava/lang/String;Ljava/lang/String;III)V
	at me.playernguyen.opteco.schedule.PointChangedPerformance.run(PointChangedPerformance.java:49)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[13:38:11] [Craft Scheduler Thread - 4887/WARN]: Exception in thread "Craft Scheduler Thread - 4887" 
[13:38:11] [Craft Scheduler Thread - 4887/WARN]: org.apache.commons.lang.UnhandledException: Plugin OptEco v2.1.3b generated an exception while executing task 220
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.sendTitle(Ljava/lang/String;Ljava/lang/String;III)V
	at me.playernguyen.opteco.schedule.PointChangedPerformance.run(PointChangedPerformance.java:49)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more    

im just getting this warn spammed in my console nonstop i made custom gui using the eco system theres nothing wrong with gui or cmds its just a warn thats getting spammed for no reason

**Comment by Maxlego08** [comment]
I have the same issue !
