### ISSUE TITLE
SQLException: Failed connect with MariaDB after 8 hours

### ISSUE THREAD

**Issue by PlayerNguyen** [PlayerNguyen/OptEco#7]
Request to add the parameter called autoConnect to true after 8 hours connect with MariaDB

The reporters has reported that they havin' a trouble with MySQL (MariaDB) connection and these Console has printed this.
````
[13:35:29] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 6,364,783 milliseconds ago.  The last packet sent successfully to the server was 6,364,783 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[13:35:29] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:35:29] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:35:29] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:35:29] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3706)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2506)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1365)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.sql.SQLAccount.executeQuery(SQLAccount.java:42)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.sql.SQLAccount.getAccountResult(SQLAccount.java:88)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.sql.SQLAccount.getAccount(SQLAccount.java:77)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.configuration.AccountLoader.hasAccount(AccountLoader.java:29)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.listener.PlayerJoinListener.onPlayerJoinEvent(PlayerJoinListener.java:18)
[13:35:29] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor106.execute(Unknown Source)
[13:35:29] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:35:29] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:35:29] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:35:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559)
[13:35:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192)
[13:35:29] [Server thread/WARN]: 	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:137)
[13:35:29] [Server thread/WARN]: 	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.joinWorld(AbstractLoginListenerPlay.java:145)
[13:35:29] [Server thread/WARN]: 	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.lambda$finishLogin$1(AbstractLoginListenerPlay.java:88)
[13:35:29] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:35:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1198)
[13:35:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[13:35:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[13:35:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[13:35:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:35:29] [Server thread/WARN]: Caused by: java.net.SocketException: Connection reset
[13:35:29] [Server thread/WARN]: 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
[13:35:29] [Server thread/WARN]: 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
[13:35:29] [Server thread/WARN]: 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[13:35:29] [Server thread/WARN]: 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3688)
[13:35:29] [Server thread/WARN]: 	... 25 more
[13:35:29] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
[13:35:29] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:35:29] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:35:29] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:35:29] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1182)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1177)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2372)
[13:35:29] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2356)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.sql.SQLAccount.executeQuery(SQLAccount.java:33)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.sql.SQLAccount.getAccountResult(SQLAccount.java:88)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.sql.SQLAccount.getAccount(SQLAccount.java:77)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.sql.SQLAccount.save(SQLAccount.java:128)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.configuration.AccountLoader.setBalance(AccountLoader.java:49)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.configuration.AccountLoader.createAccount(AccountLoader.java:23)
[13:35:29] [Server thread/WARN]: 	at me.playernguyen.listener.PlayerJoinListener.onPlayerJoinEvent(PlayerJoinListener.java:19)
[13:35:29] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor106.execute(Unknown Source)
[13:35:29] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:35:29] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:35:29] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:35:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559)
[13:35:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192)
[13:35:29] [Server thread/WARN]: 	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:137)
[13:35:29] [Server thread/WARN]: 	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.joinWorld(AbstractLoginListenerPlay.java:145)
[13:35:29] [Server thread/WARN]: 	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.lambda$finishLogin$1(AbstractLoginListenerPlay.java:88)
[13:35:29] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:35:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1198)
[13:35:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[13:35:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[13:35:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[13:35:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
````

**Comment by PlayerNguyen** [comment]
Fixed in 1.4.7b and in [this ](https://github.com/PlayerNguyen/OptEco/commit/79b47f075fed5867508dd704687bcb8b7532ed3b)commited
