### ISSUE TITLE
Trouble with RCON in 1.5b and before

### ISSUE THREAD

**Issue by PlayerNguyen** [PlayerNguyen/OptEco#9]
According to the user, the plugin having a wrong cast with AbstractCommand at line 78. This issue came from use sub-command add in RCON server. I tracked and found it easy to fix (by seperate condition). 

Exception Reporter
````
[18:10:11 WARN]: Unexpected exception while parsing console command "opteco add ku3ntin 500"                                          |
org.bukkit.command.CommandException: Unhandled exception executing command 'opteco' in plugin OptEco v1.5b                            |
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-143]                        |
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-143]                |
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-143]      |
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:714) ~[patched_1.15.2.jar:git-Paper-143]|
        at net.minecraft.server.v1_15_R1.DedicatedServer.lambda$executeRemoteCommand$3(DedicatedServer.java:722) ~[patched_1.15.2.jar:|
git-Paper-143]                                                                                                                        |
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.lambda$executeFuture$0(IAsyncTaskHandler.java:48) ~[patched_1.15.2.jar:git-|
Paper-143]                                                                                                                            |
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_242]                         |
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-143]                              |
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-143]|
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-143]    |
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-143]|
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-143]            |
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-143]   |
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-143] |
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-143]  |
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-143]            |
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]                                                                        |
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_15_R1.command.CraftRemoteConsoleCommandSender cannot be cast to org|
.bukkit.command.ConsoleCommandSender                                                                                                  |
        at me.playernguyen.opteco.command.AbstractCommand.onCommand(AbstractCommand.java:78) ~[?:?]                                   |
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-143]                        |
        ... 16 more
````

**Comment by PlayerNguyen** [comment]
Has fixed in in #715a70bf7fe37d2738a00d4d6d38f6d0cca07e67 commit
